discordbot:
  token: 
  prefix: '~'

  # commands
  createCommand: 'add'
  helpCommand: 'help'
  modifyCommand: 'edit'
  profileCommand: 'profile'
  registerCommand: 'register'
  removeCommand: 'remove'
  setColorCommand: 'setcolor'

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:rpg'
    username: 'root'
    password: ''
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  pattern:
    console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n'
